spring.application.name=game-service
spring.config.import=optional:configserver:http://config-server:8888

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://postgres-game:5432/gamedb
spring.datasource.username=game_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
